
#cors
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.host=0.0.0.0
quarkus.banner.enabled=false
quarkus.http.port=8081

# Definir nivel de log
quarkus.log.category."org.distribuidos.editorial".level=DEBUG

# Habilitar archivo
quarkus.log.file.enable=true

# Ruta del archivo (esto crea la carpeta logs si no existe)
quarkus.log.file.path=logs/autores-service.log

# Formato
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n

# Rotación diaria
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.file.rotation.rotate-on-boot=true

quarkus.rest-client.autores-api.url=http://localhost:8082
quarkus.rest-client.libros-api.url=http://localhost:8083